### PR TITLE
Release niamey

### PR DESCRIPTION
**Pull request by cehbrecht**
Updated release notes for "Niamey".

### CODE REVIEW

**Comment by Zeitsperre** [comment]
LGTM, but I'd wait for others to weigh in.

**Review by huard — APPROVED** [review]

**Review by nilshempelmann — APPROVED** [review]
Fine for me. Thanks for the work!
We could take the chance reducing the errors for the doc compilation. 
Or take it as an issue for the next release. :-)

**Review by tlvu — APPROVED** [review]
LGTM as well.

**Review by Zeitsperre — APPROVED** [review]

**Comment by cehbrecht** [comment]
> Fine for me. Thanks for the work!
> We could take the chance reducing the errors for the doc compilation.
> Or take it as an issue for the next release. :-)

There will be an Autumn release :)
https://github.com/orgs/bird-house/projects/15

**Pull request merged**
